### ISSUE TITLE
Error: This method only supports Buffer but input was: ようこそ! WalletAddress: 0x89c24a88bad4abe0a4f5b2eb5a86db1fb323832c timestamp: 1646744900349

### ISSUE THREAD

**Issue by ikmz0104** [ikmz0104/ECDSA#1]
バッファ化されていないメッセージとタイムスタンプによるエラーだと思われる。

**Comment by ikmz0104** [comment]
```js
const EthUtil = require('ethereumjs-util')
require('dotenv').config();
const env = process.env

//署名ユーザのWA（例：MetaMaskログイン時に要求される）
const SIGNER_ADDRESS_STRING = env.SIGNER_ADDRESS_STRING;
//console.log(SIGNER_ADDRESS_STRING)

//署名ユーザの秘密鍵（例：MetaMaskの秘密鍵エクスポートにて表示される内容なので公開不可能）
const PRIVATE_KEY_STRING = env.PRIVATE_KEY_STRING;
//console.log(PRIVATE_KEY_STRING)

//署名時のメッセージ（例：MetaMaskログイン時に表示される「ようこそ！」のような文言、WAやtimestamp等の備考）
const timestamp = Date.now();
const MESSAGE = 'ようこそ!\n' + 'WalletAddress: ' + SIGNER_ADDRESS_STRING + '\n' + 'timestamp: ' + timestamp;
//console.log(MESSAGE)

//受信量を緩衝する目的で秘密の文字列をバッファ化（例：abcdef ⇒ ab cd ef）
const PRIVATE_KEY = EthUtil.toBuffer(PRIVATE_KEY_STRING)
//console.log(PRIVATE_KEY)

// 与えられたメッセージと秘密鍵から署名を返すメソッド
function sign(message, privateKey) {
  //メッセージにバッファをかける
  //Todo⇒これ関数内部でやる必要なくないかな
  const hashedMessage = EthUtil.keccak(message)
  //バッファ化したメッセージと秘密鍵をもとに署名を作成します
  const Signature = EthUtil.ecsign(hashedMessage, privateKey);
  return Signature;
}

//与えられたメッセージと署名から署名者の Ethereum アドレスを導出し署名者が正しいかどうかを返すメソッド
  // 公開鍵から署名者のアドレスを計算
  // アドレスを比較


//署名を作成する
//signメソッドを呼び出す、引数にはメッセージと秘密鍵を渡す
const signature = sign(MESSAGE, PRIVATE_KEY); 
console.log(signature);






// 署名検証

```

**Comment by ikmz0104** [comment]
ww
```js
//const MESSAGE = 'ようこそ!\n' + 'WalletAddress: ' + SIGNER_ADDRESS_STRING + '\n' + 'timestamp: ' + timestamp;
const MESSAGE = 'honyohonyo'
```
Error: This method only supports Buffer but input was: honyohonyo
    at assertIsBuffer (/home/ikmz/dev/ECDSA/node_modules/ethereumjs-util/dist/helpers.js:23:15)
    at Object.keccak (/home/ikmz/dev/ECDSA/node_modules/ethereumjs-util/dist/hash.js:15:34)
    at sign (/home/ikmz/dev/ECDSA/index.js:27:33)
    at Object.<anonymous> (/home/ikmz/dev/ECDSA/index.js:40:19)

**Comment by ikmz0104** [comment]
```js
const hashedMessage = EthUtil.toBuffer(MESSAGE)
```

Error: Cannot convert string to buffer. toBuffer only supports 0x-prefixed hex strings and this string was given: honyohonyo

なるほど、. toBufferは最初に0xがつくものしかサポートしないのね
では単純な文字列をどうやってバッファしてるの
⇒https://github.com/ethereumjs/ethereumjs-util

**Comment by ikmz0104** [comment]
これだああ
https://github.com/ethereumjs/ethereumjs-util/blob/master/docs/modules/_hash_.md#const-keccakfromstring

**Comment by ikmz0104** [comment]
timestamp入れてもOKやった
```js
const timestamp = Date.now();
const MESSAGE = 'ようこそ!\n' + 'WalletAddress: ' + SIGNER_ADDRESS_STRING + '\n' + 'timestamp: ' + timestamp;
```

```
$ node index.js
{
  r: <Buffer b9 5f f4 a0 29 67 62 4d 92 12 60 93 44 8a 65 8f 53 07 ab 52 85 5c 54 59 5c 7e 90 ed de 87 6f 12>,
  s: <Buffer 46 d8 b9 15 1d 4b a8 d2 4f ad b1 a1 be bd 8b 5b 18 31 5c 4c e4 1b ff 15 6a 16 e6 82 96 33 8d d7>,
  v: 27
}
```

**Comment by ikmz0104** [comment]
で、やっぱり関数内部でバッファ化するの意味わからんから外に出したい。
↓
OK
```js
function sign(message, privateKey) {
  const hashedMessage = message;
  const Signature = EthUtil.ecsign(hashedMessage, privateKey);
  return Signature;
}

const signature = sign(HASHED_MESSAGE, PRIVATE_KEY); 
console.log(signature);


```

**Comment by ikmz0104** [comment]
https://github.com/ikmz0104/ECDSA/commit/f00bc32b7b78b69cba78f44a0b017840d31ff8f9
